name: Push to Docker Hub on Release
on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Branch
    - uses: actions/checkout@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
    - run: npm ci
      
    - name: Build and start Container
    - run: npm run start:prodname
    
    - name: Publish to Registry
    - run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag inspector-f ${{ secrets.DOCKER_USERNAME }}/inspector-f
        docker push ${{ secrets.DOCKER_USERNAME }}/inspector-f
        
